services:
  ollama-server:
    container_name: ollama
    image: ollama/ollama
    volumes:
      - ./ollama:/root/.ollama
    restart: always
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CHROMA_DIR=${CHROMA_DIR}
      - DATA_DIR=${DATA_DIR}
    volumes:
      - ${CHROMA_DIR}:/app/${CHROMA_DIR}
      - ${DATA_DIR}:/app/${DATA_DIR}
    restart: unless-stopped