services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CHROMA_DIR=${CHROMA_DIR}
      - DATA_DIR=${DATA_DIR}
      - GIGACHAT_CLIENT_ID=${GIGACHAT_CLIENT_ID}
      - GIGACHAT_CLIENT_SECRET=${GIGACHAT_CLIENT_SECRET}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ${CHROMA_DIR}:/app/${CHROMA_DIR}
      - ${DATA_DIR}:/app/${DATA_DIR}
    restart: unless-stopped