services:
  bot:
    image: alexkhrist/rag-bot:latest
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CHROMA_DIR=${CHROMA_DIR}
      - DATA_DIR=${DATA_DIR}
      - GIGACHAT_CLIENT_ID=${GIGACHAT_CLIENT_ID}
      - GIGACHAT_CLIENT_SECRET=${GIGACHAT_CLIENT_SECRET}
      - DEBUG=${DEBUG}
      - BUILD_INDEX=${BUILD_INDEX}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
    volumes:
      - ${CHROMA_DIR}:/app/${CHROMA_DIR}
      - ${DATA_DIR}:/app/${DATA_DIR}